class MenuEntity {
  final int id;
  final String name;
  final int? quantity;
  final double cost;
  final String? weight;
  final int categoryId;
  final bool isSpicy;
  final bool isVegan;
  final List<int>? ingredients;
  final List<String>? images;
  final List<int>? labels;
  final List<int>? menuPositions;

  const MenuEntity({
    required this.id,
    required this.name,
    this.quantity,
    required this.cost,
    this.weight,
    required this.categoryId,
    this.isSpicy = false,
    this.isVegan = false,
    this.ingredients,
    this.images,
    this.labels,
    this.menuPositions,
  });

  static const List<MenuEntity> menuList = [
    MenuEntity(
        id: 1,
        name: 'Спагетти Карбонара',
        quantity: 10,
        cost: 12.99,
        weight: '250г',
        categoryId: 1,
        isSpicy: true,
        isVegan: false,
        ingredients: [1, 2, 3],
        images: ['image1.png', 'image2.png'],
        labels: [1],
        menuPositions: [1, 2]),
    MenuEntity(
        id: 2,
        name: 'Салат Цезарь',
        quantity: 15,
        cost: 8.50,
        weight: '200г',
        categoryId: 2,
        isSpicy: false,
        isVegan: false,
        ingredients: [4, 5, 6],
        images: ['image3.png', 'image4.png'],
        labels: [2],
        menuPositions: [3]),
    MenuEntity(
        id: 3,
        name: 'Пицца Маргарита',
        quantity: 20,
        cost: 9.99,
        weight: '300г',
        categoryId: 3,
        isSpicy: true,
        isVegan: true,
        ingredients: [7, 8, 9],
        images: ['image5.png', 'image6.png'],
        labels: [3],
        menuPositions: [4, 5]),
    MenuEntity(
        id: 4,
        name: 'Сэндвич с курицей гриль',
        quantity: 8,
        cost: 7.99,
        weight: '150г',
        categoryId: 4,
        isSpicy: true,
        isVegan: false,
        ingredients: [10, 11, 12],
        images: ['image7.png'],
        labels: [1],
        menuPositions: [6]),
    MenuEntity(
        id: 5,
        name: 'Овощное жаркое',
        quantity: 12,
        cost: 11.00,
        weight: '200г',
        categoryId: 5,
        isSpicy: true,
        isVegan: true,
        ingredients: [13, 14, 15],
        images: ['image8.png', 'image9.png'],
        labels: [4],
        menuPositions: [7, 8]),
    MenuEntity(
        id: 6,
        name: 'Тортилья с говядиной',
        quantity: 10,
        cost: 5.99,
        weight: '180г',
        categoryId: 6,
        isSpicy: true,
        isVegan: false,
        ingredients: [16, 17, 18],
        images: ['image10.png'],
        labels: [5],
        menuPositions: [9]),
    MenuEntity(
        id: 7,
        name: 'Манговый смузи',
        quantity: 20,
        cost: 4.50,
        weight: '250мл',
        categoryId: 7,
        isSpicy: false,
        isVegan: true,
        ingredients: [19, 20, 21],
        images: ['image11.png'],
        labels: [6],
        menuPositions: [10]),
    MenuEntity(
        id: 8,
        name: 'Ребрышки BBQ',
        quantity: 5,
        cost: 15.99,
        weight: '350г',
        categoryId: 8,
        isSpicy: true,
        isVegan: false,
        ingredients: [22, 23, 24],
        images: ['image12.png'],
        labels: [7],
        menuPositions: [11, 12]),
    MenuEntity(
        id: 9,
        name: 'Шоколадный торт',
        quantity: 8,
        cost: 6.99,
        weight: '150г',
        categoryId: 9,
        isSpicy: false,
        isVegan: false,
        ingredients: [25, 26, 27],
        images: ['image13.png'],
        labels: [8],
        menuPositions: [13]),
    MenuEntity(
        id: 10,
        name: 'Тост с авокадо',
        quantity: 10,
        cost: 5.50,
        weight: '120г',
        categoryId: 10,
        isSpicy: false,
        isVegan: true,
        ingredients: [28, 29, 30],
        images: ['image14.png'],
        labels: [9],
        menuPositions: [14]),
    MenuEntity(
        id: 11,
        name: 'Лосось на гриле',
        quantity: 7,
        cost: 13.99,
        weight: '200г',
        categoryId: 1,
        isSpicy: true,
        isVegan: false,
        ingredients: [31, 32, 33],
        images: ['image15.png'],
        labels: [10],
        menuPositions: [15]),
    MenuEntity(
        id: 12,
        name: 'Греческий салат',
        quantity: 10,
        cost: 7.99,
        weight: '150г',
        categoryId: 2,
        isSpicy: false,
        isVegan: false,
        ingredients: [34, 35, 36],
        images: ['image16.png'],
        labels: [11],
        menuPositions: [16]),
    MenuEntity(
        id: 13,
        name: 'Пицца Пепперони',
        quantity: 20,
        cost: 10.99,
        weight: '300г',
        categoryId: 3,
        isSpicy: true,
        isVegan: false,
        ingredients: [37, 38, 39],
        images: ['image17.png'],
        labels: [12],
        menuPositions: [17, 18]),
    MenuEntity(
        id: 14,
        name: 'Куриные крылышки',
        quantity: 15,
        cost: 9.99,
        weight: '250г',
        categoryId: 4,
        isSpicy: true,
        isVegan: false,
        ingredients: [40, 41, 42],
        images: ['image18.png'],
        labels: [13],
        menuPositions: [19]),
    MenuEntity(
        id: 15,
        name: 'Жаркое с тофу',
        quantity: 12,
        cost: 10.00,
        weight: '200г',
        categoryId: 5,
        isSpicy: true,
        isVegan: true,
        ingredients: [43, 44, 45],
        images: ['image19.png'],
        labels: [14],
        menuPositions: [20, 21]),
    MenuEntity(
        id: 16,
        name: 'Тортилья с рыбой',
        quantity: 8,
        cost: 6.99,
        weight: '180г',
        categoryId: 6,
        isSpicy: true,
        isVegan: false,
        ingredients: [46, 47, 48],
        images: ['image20.png'],
        labels: [1, 4],
        menuPositions: [22]),
    MenuEntity(
        id: 17,
        name: 'Клубничный смузи',
        quantity: 18,
        cost: 4.99,
        weight: '250мл',
        categoryId: 7,
        isSpicy: false,
        isVegan: true,
        ingredients: [49, 50, 51],
        images: ['image21.png'],
        labels: [2, 11],
        menuPositions: [23]),
    MenuEntity(
        id: 18,
        name: 'Свинина на косточке',
        quantity: 5,
        cost: 16.99,
        weight: '350г',
        categoryId: 8,
        isSpicy: true,
        isVegan: false,
        ingredients: [52, 53, 54],
        images: ['image22.png'],
        labels: [5],
        menuPositions: [24, 25]),
    MenuEntity(
        id: 19,
        name: 'Чизкейк',
        quantity: 7,
        cost: 7.99,
        weight: '150г',
        categoryId: 9,
        isSpicy: false,
        isVegan: false,
        ingredients: [55, 56, 57],
        images: ['image23.png'],
        labels: [9],
        menuPositions: [26]),
    MenuEntity(
        id: 20,
        name: 'Паста с морепродуктами',
        quantity: 9,
        cost: 14.99,
        weight: '250г',
        categoryId: 10,
        isSpicy: true,
        isVegan: false,
        ingredients: [58, 59, 60],
        images: ['image24.png'],
        labels: [2, 6],
        menuPositions: [27]),
    MenuEntity(
        id: 21,
        name: 'Панини с ветчиной и сыром',
        quantity: 10,
        cost: 6.50,
        weight: '200г',
        categoryId: 1,
        isSpicy: true,
        isVegan: false,
        ingredients: [61, 62, 63],
        images: ['image25.png'],
        labels: [4, 8],
        menuPositions: [28]),
    MenuEntity(
        id: 22,
        name: 'Тайский карри с овощами',
        quantity: 8,
        cost: 12.50,
        weight: '300г',
        categoryId: 2,
        isSpicy: true,
        isVegan: true,
        ingredients: [64, 65, 66],
        images: ['image26.png'],
        labels: [4],
        menuPositions: [29]),
    MenuEntity(
        id: 23,
        name: 'Блины с фруктами',
        quantity: 12,
        cost: 8.00,
        weight: '150г',
        categoryId: 3,
        isSpicy: false,
        isVegan: true,
        ingredients: [67, 68, 69],
        images: ['image27.png'],
        labels: [13],
        menuPositions: [30]),
    MenuEntity(
        id: 24,
        name: 'Французский луковый суп',
        quantity: 5,
        cost: 7.50,
        weight: '200г',
        categoryId: 4,
        isSpicy: true,
        isVegan: false,
        ingredients: [70, 71, 72],
        images: ['image28.png'],
        labels: [5],
        menuPositions: [31]),
    MenuEntity(
        id: 25,
        name: 'Рататуй',
        quantity: 6,
        cost: 9.99,
        weight: '250г',
        categoryId: 5,
        isSpicy: true,
        isVegan: true,
        ingredients: [73, 74, 75],
        images: ['image29.png'],
        labels: [1, 2],
        menuPositions: [32]),
  ];
}
